### PR TITLE
Update the project to the nowadays firebase version

### PR DESCRIPTION
**Pull request by MountainLovers**
1. Rewrite the server.js. In old version, index.html can not be opened. 
2. Update the firebase config.

### CODE REVIEW

**Comment by otiai10** [comment]
Thanks. Let me check.

**Comment by otiai10** [comment]
@MountainLovers 
Thank you for sending the pull-request.

As I checked, there was a fatal error on `server.js` and this is my fix for that: https://github.com/otiai10/firebase-messaging-sample/commit/8ea7464add97886944f203379014f85ab4fafea7
Please check it out.

**EXCEPT THAT**, I couldn't see any problems and can see push-notifications working well.

I'd like you to give me more information or purpose of this pull-request. Thanks 😉

**Comment by otiai10** [comment]
@MountainLovers ping

**Comment by MountainLovers** [comment]
> @MountainLovers ping

Sorry for late! I will review my code. Thank you!

**Pull request closed without merging**
